### ISSUE TITLE
Add to MELPA

### ISSUE THREAD

**Issue by ferfebles** [sheijk/hideshowvis#1]
Since 2015 there were talks in MELPA about depreciating all 'emacswiki' packages because "anyone can edit your package(s) on the Emacswiki and that poses a security risk".

Finally on 24 Jan, @milkipostman "inadvertently deleted all emacswiki packages", which was probably a good thing.

The problem is that I'm very fond of 'hideshowvis', and I have an automated emacs install that is failing because hideshowvis can't be found (obviously I'm installing it by hand).

Could you add this library to MELPA (or ELPA)?

**Comment by sheijk** [comment]
Planning to do that at some time. I think the reason it’s not there yet was that Melpa required tests for the package. I’m travelling right now so won’t get around to do this too soon, though

**Comment by ferfebles** [comment]
MELPA does not requires tests for your package. You only have to fork the project, add a recipe for your package and send a pull request. I sent a package called 'redtick' and they even gave me some advice about it.

Your recipe will be something like this:

`(hideshowvis :fetcher github :repo "sheijk/hideshowvis")`

The only thing they ask you to test, is the build process before sending the pull request: adding your recipe to the forked MELPA, and running `make recipes/hideshowvis`

More info in [contributing](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md)

**Comment by treymerkley** [comment]
I did the same thing, and I'm not even a heavy Lisper. I'll second that this needs to be in MELPA.

**Comment by IAMSolaara** [comment]
bumping this, I can't figure out how to install this so having the package on MELPA would help

**Comment by andreyorst** [comment]
Wanted to install this, but it's available only on marmalade, which `https` certificate expired.

Maybe instead of uploading to Melpa contribute the code to the `hideshow.el` directly? It seem to be a good built in feature. And will probably make it easier to maintain the package later as part of Emacs which `hideshow.el` already is.

**Comment by sheijk** [comment]
Hideshowvis has been added to NonGNU Elpa a few days ago. See [here](https://elpa.nongnu.org/nongnu/hideshowvis.html)

**Comment by ferfebles** [comment]
Tested and working great.

Thanks!!!
