### ISSUE TITLE
Symbol's function definition is void: hideshowvis-symbols

### ISSUE THREAD

**Issue by jimtut** [sheijk/hideshowvis#6]
When I place the following code in my init.el file:
```
(autoload 'hideshowvis-enable "hideshowvis" "Highlight foldable regions")

(autoload 'hideshowvis-minor-mode
   "hideshowvis"
   "Will indicate regions foldable with hideshow in the fringe."
   'interactive)

(dolist (hook (list 
  'emacs-lisp-mode-hook
	'json-mode-hook
  'c++-mode-hook
  'python-mode ;; doesn't work?
  'perl-mode ;; doesn't work?
  ))
  (add-hook hook 'hideshowvis-enable))
(hideshowvis-symbols)
```

I get the following error:
`Symbol's function definition is void: hideshowvis-symbols`

If I remove that line and run hideshowvis-symbols interactively, it works.

How come it doesn't work when run in init.el?

**Comment by mookid** [comment]
what about replacing with python-mode-hook / perl-mode-hook?

**Comment by jimtut** [comment]
Oh, you're right about the perl/python hooks, well, at least for Perl (doesn't seem to work in Python).

But, my question is about the last line (hideshowvis-symbols).  That's giving an error when it's in the init file.  BTW, I'm on a Mac, if that matters, but it's the same whether I use a Terminal-based emacs or a full GUI version.

I can run that command interactively, but I can't leave it in the init file or I get an error, and the rest of the init file doesn't load.  It's like that command can't be run unless hideshow-minor-mode is already active/enabled.

That gave me an idea - I just added "(hideshowvis-enable)" before "(hideshowvis-symbols)" and it seems to work!  Maybe that should be in the docs, or am I still doing something wrong?

**Comment by sheijk** [comment]
The problem is that `hideshowvis-symbols` needs an autoload, too. So add

```
(autoload 'hideshowvis-symbols)
```
after the other autoload. Or as you're calling the function and thus immediately loading the mode you could just `(require 'hideshowvis)` instead of the autoload

**Comment by jimtut** [comment]
Sorry, I'm not a lisp/emacs expert, but isn't there a way to hook into the hideshowvis-minor-mode, and "run" (?) hideshowvis-symbols everytime the mode is active?  That seems the most efficient to me (or I could just edit my copy of the source EL file too, I guess?).

**Comment by sheijk** [comment]
Sorry, lost track of your comment. You only need to run this function once. Running it again will only redefine a bunch of functions and would be unneeded. You could also add something like this to call it after hideshowvis gets loaded:
```
(with-eval-after-load 'hideshowvis (hideshowvis-symbols)
```
to call it only once after hideshowvis gets loaded. That should also have a small advantage for Emacs startup time.
